test<-read.table("./test/X_test.txt")
train<-read.table("./train/X_train.txt")
train_sub<-read.table("./train/subject_train.txt")
test_sub<-read.table("./test/subject_test.txt")
test_activity<-read.table("./test/y_test.txt")
features<-read.table("features.txt")
train_activity<-read.table("./train/y_train.txt")
colnames(test)<-features[,2]
colnames(train)<-features[,2]
colnames(test_sub)<-c("subject")
colnames(train_sub)<-c("subject")
colnames(test_activity)<-c("activity")
colnames(train_activity)<-c("activity")
test_act<-cbind(test_activity,test)
test_act_sub<-cbind(test_sub,test_act)
train_act<-cbind(train_activity,train)
train_act_sub<-cbind(train_sub,train_act)
dataset<-rbind(train_act_sub,test_act_sub)

dataset[,2]<-gsub(1,"WALKING",dataset[,2])
dataset[,2]<-gsub(2,"WALKING_UPSTAIRS",dataset[,2])
dataset[,2]<-gsub(3,"WALKING_DOWNSTAIRS",dataset[,2])
dataset[,2]<-gsub(4,"SITTING",dataset[,2])
dataset[,2]<-gsub(5,"STANDING",dataset[,2])
dataset[,2]<-gsub(6,"LAYING",dataset[,2])
names<-colnames(dataset)
sub<-grep("mean",names)
sub_std<-grep("std",names)
data_final<-cbind(dataset[,1:2],dataset[,sub],dataset[,sub_std])
data_final<-group_by(data_final,subject,activity)
final<-summarize_all(data_final,funs(mean))

                      